package model;

// Generated 18-feb-2015 17:38:30 by Hibernate Tools 3.4.0.CR1

/**
 * Preguntas generated by hbm2java
 */
public class Preguntas implements java.io.Serializable {

	private Integer idPreguntas;
	private String titulo;
	private String categoria;
	private String imagen;
	private int fidPreguntas;
	private String tipo;
	private String consejo;

	
	public Preguntas(String titulo, String categoria, String imagen,
			int fidPreguntas) {
		this.titulo = titulo;
		this.categoria = categoria;
		this.imagen = imagen;
		this.fidPreguntas = fidPreguntas;
	}

	public Preguntas(String titulo, String categoria, String imagen,
			int fidPreguntas, String tipo, String consejo) {
		this.titulo = titulo;
		this.categoria = categoria;
		this.imagen = imagen;
		this.fidPreguntas = fidPreguntas;
		this.tipo = tipo;
		this.consejo = consejo;
	}

	public Integer getIdPreguntas() {
		return this.idPreguntas;
	}

	public void setIdPreguntas(Integer idPreguntas) {
		this.idPreguntas = idPreguntas;
	}

	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	public String getCategoria() {
		return this.categoria;
	}

	public void setCategoria(String categoria) {
		this.categoria = categoria;
	}

	public String getImagen() {
		return this.imagen;
	}

	public void setImagen(String imagen) {
		this.imagen = imagen;
	}

	public int getFidPreguntas() {
		return this.fidPreguntas;
	}

	public void setFidPreguntas(int fidPreguntas) {
		this.fidPreguntas = fidPreguntas;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public String getConsejo() {
		return this.consejo;
	}

	public void setConsejo(String consejo) {
		this.consejo = consejo;
	}

}
