package model;

// Generated 18-feb-2015 17:38:30 by Hibernate Tools 3.4.0.CR1

/**
 * Respuestas generated by hbm2java
 */
public class Respuestas implements java.io.Serializable {

	private Integer idRespuestas;
	private String respuesta;
	private Boolean solucion;
	private Integer idPreguntas;

	public Respuestas(String respuesta, Boolean solucion, Integer idPreguntas) {
		this.respuesta = respuesta;
		this.solucion = solucion;
		this.idPreguntas = idPreguntas;
	}

	public Integer getIdRespuestas() {
		return this.idRespuestas;
	}

	public void setIdRespuestas(Integer idRespuestas) {
		this.idRespuestas = idRespuestas;
	}

	public String getRespuesta() {
		return this.respuesta;
	}

	public void setRespuesta(String respuesta) {
		this.respuesta = respuesta;
	}

	public Boolean getSolucion() {
		return this.solucion;
	}

	public void setSolucion(Boolean solucion) {
		this.solucion = solucion;
	}

	public Integer getIdPreguntas() {
		return this.idPreguntas;
	}

	public void setIdPreguntas(Integer idPreguntas) {
		this.idPreguntas = idPreguntas;
	}

}
